#!/usr/bin/env python

import sys
import fileconversions


if __name__ == '__main__':

    target_format = sys.argv[1]
    source_path = sys.argv[2]

    if target_format != 'pdf':
        print('Conversion not implemented.')
        sys.exit(1)

    engine = fileconversions.ConversionEngine()

    conversion = engine.get_conversion(
        fileconversions.file_format_from_filepath(source_path),
        fileconversions.FileFormats.PDF
    )

    target_path = conversion(source_path)

    print('File available at {}'.format(target_path))

    sys.exit(0)
